### ISSUE TITLE
Allow custom service domains

### ISSUE THREAD

**Issue by gavlinski** [hbstack/content-panel#36]
Please add support for custom url addresses for services, like an internal GitLab server at https://mygitlab.com.br

```yaml
  content_panel:
    repo:
      service: gitlab # github or gitlab.
      custom_url: https://mygitlab.com.br
      repo: group/project/subproject
      branch: main
```
